### ISSUE TITLE
issue with libcpu & latest llvm

### ISSUE THREAD

**Issue by ghost** [libcpu/libcpu#3]
stephen@karma:~/compileZone/libcpu/arch/6502$ cd /home/stephen/compileZone/libcpu/arch/6502 && /usr/bin/c++   -D__STDC_FORMAT_MACROS=1 -I/usr/lib/llvm-3.5/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -ffunction-sections -fdata-sections -Wcast-qual -g -I/home/stephen/compileZone/libcpu/libcpu -I/usr/lib/llvm-3.5/include -I/home/stephen/compileZone/libcpu    -W -Wall -Wextra -Wno-unused -Wno-unused-parameter -o CMakeFiles/6502.dir/6502_translate.cpp.o -c 
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp 

In file included from /home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:12:0:
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp: In function âllvm::Value\* arch_6502_get_operand_lvalue(cpu_t_, addr_t, llvm::BasicBlock_)â:
/home/stephen/compileZone/libcpu/libcpu/frontend.h:58:21: error: incomplete type âllvm::ConstantIntâ used in nested name specifier
 #define CONSTs(s,v) ConstantInt::get(getIntegerType(s), v)
                     ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:60:19: note: in expansion of macro âCONSTsâ
 #define CONST8(v) CONSTs(8,v)
                   ^
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:55:18: note: in expansion of macro âCONST8â
    new StoreInst(CONST8(OPERAND_8), ptr_temp, bb);
                  ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:58:21: error: incomplete type âllvm::ConstantIntâ used in nested name specifier
 #define CONSTs(s,v) ConstantInt::get(getIntegerType(s), v)
                     ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:62:20: note: in expansion of macro âCONSTsâ
 #define CONST32(v) CONSTs(32,v)
                    ^
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:79:14: note: in expansion of macro âCONST32â
  Value *ea = CONST32(base);
              ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:58:21: error: incomplete type âllvm::ConstantIntâ used in nested name specifier
 #define CONSTs(s,v) ConstantInt::get(getIntegerType(s), v)
                     ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:95:62: note: in definition of macro âANDâ
 #define AND(a,b) BinaryOperator::Create(Instruction::And, a, b, "", bb)
                                                              ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:62:20: note: in expansion of macro âCONSTsâ
 #define CONST32(v) CONSTs(32,v)
                    ^
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:86:16: note: in expansion of macro âCONST32â
   ea = AND(ea, CONST32(0x00FF));
                ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:58:21: error: incomplete type âllvm::ConstantIntâ used in nested name specifier
 #define CONSTs(s,v) ConstantInt::get(getIntegerType(s), v)
                     ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:95:62: note: in definition of macro âANDâ
 #define AND(a,b) BinaryOperator::Create(Instruction::And, a, b, "", bb)
                                                              ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:62:20: note: in expansion of macro âCONSTsâ
 #define CONST32(v) CONSTs(32,v)
                    ^
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:88:16: note: in expansion of macro âCONST32â
   ea = AND(ea, CONST32(0xFFFF));

**Comment by sleary78** [comment]
Which gcc/llvm did you use for this branch? I still have some issues building your branch but not as many as the trunk

**Comment by sleary78** [comment]
I basically see the same issue with your branch and trunk when using gcc 4.9

**Comment by nathanjackson** [comment]
I used GCC 4.8 and I don't remember the LLVM version.  For the time being, I've actually not done any work on devel because for the project I am working we need ARM support.  Reading through old commits and old mailing lists, it looks like ARM stopped working at some point.  So I went back and found a known working commit and started there and I am currently adding various instructions and updating it to work with LLVM 3.5 and GCC 4.9 (Fedora 21).  For my testing thus far, I've had to go all the way back to LLVM 2.6.  That should change in the next week hopefully.

**Comment by penberg** [comment]
I have a branch here to make things work with LLVM 8.0:

https://github.com/libcpu/libcpu/tree/llvm-8

Things that need to be resolved to make it actually work:

* Push `LLVMContext` to `cpu_t`, for example, to get around the removed `getGlobalContext()` function.
* Make libcpu work with the new LLVM JIT APIs, which seem to be significantly different than before.

**Comment by penberg** [comment]
The `LLVMContext` issue is now resolved in the branch.

**Comment by penberg** [comment]
The JIT issue is also resolved now. The changes need some more testing, of course, but the API adjustment work is now complete.
