### PR TITLE
Fix libcpu build with LLVM 8.0

### LINKED ISSUE #3: issue with libcpu & latest llvm
stephen@karma:~/compileZone/libcpu/arch/6502$ cd /home/stephen/compileZone/libcpu/arch/6502 && /usr/bin/c++   -D__STDC_FORMAT_MACROS=1 -I/usr/lib/llvm-3.5/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -ffunction-sections -fdata-sections -Wcast-qual -g -I/home/stephen/compileZone/libcpu/libcpu -I/usr/lib/llvm-3.5/include -I/home/stephen/compileZone/libcpu    -W -Wall -Wextra -Wno-unused -Wno-unused-parameter -o CMakeFiles/6502.dir/6502_translate.cpp.o -c 
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp 

In file included from /home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:12:0:
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp: In function âllvm::Value\* arch_6502_get_operand_lvalue(cpu_t_, addr_t, llvm::BasicBlock_)â:
/home/stephen/compileZone/libcpu/libcpu/frontend.h:58:21: error: incomplete type âllvm::ConstantIntâ used in nested name specifier
 #define CONSTs(s,v) ConstantInt::get(getIntegerType(s), v)
                     ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:60:19: note: in expansion of macro âCONSTsâ
 #define CONST8(v) CONSTs(8,v)
                   ^
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:55:18: note: in expansion of macro âCONST8â
    new StoreInst(CONST8(OPERAND_8), ptr_temp, bb);
                  ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:58:21: error: incomplete type âllvm::ConstantIntâ used in nested name specifier
 #define CONSTs(s,v) ConstantInt::get(getIntegerType(s), v)
                     ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:62:20: note: in expansion of macro âCONSTsâ
 #define CONST32(v) CONSTs(32,v)
                    ^
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:79:14: note: in expansion of macro âCONST32â
  Value *ea = CONST32(base);
              ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:58:21: error: incomplete type âllvm::ConstantIntâ used in nested name specifier
 #define CONSTs(s,v) ConstantInt::get(getIntegerType(s), v)
                     ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:95:62: note: in definition of macro âANDâ
 #define AND(a,b) BinaryOperator::Create(Instruction::And, a, b, "", bb)
                                                              ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:62:20: note: in expansion of macro âCONSTsâ
 #define CONST32(v) CONSTs(32,v)
                    ^
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:86:16: note: in expansion of macro âCONST32â
   ea = AND(ea, CONST32(0x00FF));
                ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:58:21: error: incomplete type âllvm::ConstantIntâ used in nested name specifier
 #define CONSTs(s,v) ConstantInt::get(getIntegerType(s), v)
                     ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:95:62: note: in definition of macro âANDâ
 #define AND(a,b) BinaryOperator::Create(Instruction::And, a, b, "", bb)
                                                              ^
/home/stephen/compileZone/libcpu/libcpu/frontend.h:62:20: note: in expansion of macro âCONSTsâ
 #define CONST32(v) CONSTs(32,v)
                    ^
/home/stephen/compileZone/libcpu/arch/6502/6502_translate.cpp:88:16: note: in expansion of macro âCONST32â
   ea = AND(ea, CONST32(0xFFFF));

### PR DESCRIPTION
**Pull request by penberg**
This pull request makes `libcpu` build with LLVM 8.0.

Fixes #3

### CODE REVIEW

File: libcpu/interface.cpp [hunk 1]
```diff
@@ -180,14 +184,17 @@ cpu_new(cpu_arch_t arch, uint32_t flags, uint32_t arch_flags)
 	}
 
 	// init LLVM
-	cpu->mod = new Module(cpu->info.name, _CTX());
```
[the remark this answers is not in the document]
Comment (penberg) [reply libcpu/interface.cpp]: Good catch! It was from a different approach that I tried out (before I figured out that overriding `_CTX` is much simpler). Will fix.

File: libcpu/interface.cpp [hunk 2]
```diff
@@ -85,6 +88,7 @@ cpu_new(cpu_arch_t arch, uint32_t flags, uint32_t arch_flags)
 	memset(&cpu->info, 0, sizeof(cpu->info));
 	memset(&cpu->rf, 0, sizeof(cpu->rf));
 
+	cpu->ctx = new LLVMContext(); // FIXME: release memory
```
[the remark this answers is not in the document]
Comment (penberg) [reply libcpu/interface.cpp]: No, will fix, thanks!
